name: 's3-multibranch-deploy-preview'

description: 'Deploy preview of your frontend to S3 bucket for each branch in repository'

inputs:
  aws_region:
    description: 'AWS region of the S3 bucket'
    default: 'us-east-1'
    required: true
  aws_assume_role:
    description: 'ARN of the role to be assumed'
    default: ''
    required: true
  aws_bucket:
    description: 'Name of the S3 bucket'
    default: ''
    required: true
  folder:
    description: 'Folder to be deployed in S3 bucket'
    default: './site'
    required: true
  max_branch_deployed:
    description: 'Maximum number of branches to be deployed'
    default: '50'
    required: false
  max_commit_per_branch_deployed:
    description: 'Maximum number of commit per branch to be deployed'
    default: '10'
    required: false
  prefix:
    description: 'Prefix path for base url'
    default: ''
    required: false
  generate_prefix:
    description: 'Generate prefix for each branch'
    default: 'false'
    required: false

outputs:
  preview_url:
    description: 'URL of the deployed preview'
    value: ${{ steps.deploy.outputs.preview_url }}

runs:
  using: composite
  steps:

  - name: configure AWS credentials
    id: creds
    if: ${{ inputs.generate_prefix == 'false' }}
    uses: aws-actions/configure-aws-credentials@v1
    with:
      role-to-assume: ${{ inputs.aws_assume_role }}
      role-session-name: samplerolesession
      aws-region: ${{ inputs.aws_region }}

  - name: Set GitHub Path
    run: echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
    shell: bash
    env:
      GITHUB_ACTION_PATH: ${{ github.action_path }}

  - name: Generate prefix
    if: ${{ inputs.generate_prefix == 'true' }}
    id: prefix
    run: generate_prefix.sh
    shell: bash

  - name: Deploy preview
    id: deploy
    if: ${{ inputs.generate_prefix == 'false' }}
    shell: bash
    run: entrypoint.sh
    env:
      INPUT_AWS_BUCKET: ${{ inputs.aws_bucket }}
      INPUT_AWS_REGION: ${{ inputs.aws_region }}
      INPUT_FOLDER: ${{ inputs.folder }}
      INPUT_MAX_BRANCH_DEPLOYED: ${{ inputs.max_branch_deployed }}
      INPUT_MAX_COMMIT_PER_BRANCH_DEPLOYED: ${{ inputs.max_commit_per_branch_deployed }}
      INPUT_PREFIX: ${{ inputs.prefix }}
